# Generated by Django 3.2.16 on 2023-02-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectification', '0002_auto_20230202_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='is sent to elastic'),
        ),
    ]
